name: Build and Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
    # 1. Checkout code from main branch
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        ref: main

    - name: Install Java and Gradle
      run: |
        sudo apt install git
        git clone https://github.com/pradeepkaturi/Hypha-learning.git

    # 5. Deploy to EC2
    - name: Deploy to EC2
      env:
        EC2_HOST: 44.220.162.146
        EC2_USER: ec2-user
      run: |
        pwd
        ls -ltr
        chmod 400 ec2-key.pem
        ls -ltr
        ssh -o StrictHostKeyChecking=no -i "ec2-key.pem" $EC2_USER@$EC2_HOST << 'EOF'
        sudo yum update -y
        sudo yum install git
        git clone https://github.com/pradeepkaturi/Hypha-learning.git
        sudo yum install java-17-amazon-corretto-devel
        wget https://services.gradle.org/distributions/gradle-8.10.2-bin.zip -P /tmp
        sudo unzip -d /opt/ /tmp/gradle-8.10.2-bin.zip
        sudo ln -s /opt/gradle-8.10.2 /opt/gradle
        echo "export PATH=\$PATH:/opt/gradle/bin" | sudo tee /etc/profile.d/gradle.sh
        sudo chmod +x /etc/profile.d/gradle.sh
        source /etc/profile.d/gradle.sh
        gradle -v
        cd /home/ec2-user/Hypha-learning/java_demo_app/build/libs
        nohup java -jar my-java-app.jar > app.log 2>&1 &
        sleep 5
        tail -n 20 app.log
        EOF
