name: Build Java Demo App and Upload to Docker Hub

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # 1. Checkout code from main branch
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        ref: main

    - name: Install Java and Gradle
      run: |
        sudo apt install git
        git clone https://github.com/pradeepkaturi/Hypha-learning.git
        
    - name: Build App using Grade
      run: |
        ls -ltr
        cd java_demo_app
        ls -ltr
        gradle -v
        gradle init
        ./gradlew clean build
        ls -ltr        

  build_docker_mage:
    runs-on: ubuntu-latest
    needs:  build
  
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Build Image
        run: |
          docker build -t demo_java_app:latest .

      - name: Login to Docker hub
        uses: docker/login-action@v1
        with:
          username: $MY_GIT_HUB_USER_NAME
          password: $MY_GIT_HUB_PASSWORD
        env:
          MY_GIT_HUB_USER_NAME: ${{ secrets.GIT_HUB_USER_NAME }}
          MY_GIT_HUB_PASSWORD: ${{ secrets.GIT_HUB_PASSWORD }}

      - name: Push image to Docker Hub
        run: docker push pradeepkaturi/practice:latest