name: Build Java Demo App and Upload to Docker Hub

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # 1. Checkout code from main branch
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        ref: main

    - name: Install Java and Gradle
      run: |
        sudo apt install git
        git clone https://github.com/pradeepkaturi/Hypha-learning.git
        
    - name: Set up Gradle
      uses: gradle/actions/setup-gradle@v3
      with:
        gradle-version: 8.10

    - name: Build App using Grade
      run: |
        ls -ltr
        cd java_demo_app
        ls -ltr
        gradle -v
        gradle wrapper
        ls -ltr
        ./gradlew build 
        ls -ltr
        cd build/libs
        ls -ltr
        pwd

    - name: Build Image
      run: |
        ls -ltr
        pwd
        cd java_demo_app
        docker build -t practice:latest .
         ls -ltr
        pwd

    - name: Login to Docker hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.GIT_HUB_USER_NAME }}
        password: ${{ secrets.GIT_HUB_PASSWORD }}
        
    - name: Push image to Docker Hub
      run: docker push pradeepkaturi/practice:latest